investors:
  - id: "1067983"
    name: Berkshire Hathaway
  - id: "1336528"
    name: Pershing Square
  - id: "1656456"
    name: Appaloosa
  - id: "1040273"
    name: Third Point
  - id: "1029160"
    name: Soros Fund Management
  - id: "1536411"
    name: Duquesne Family Office
  - id: "1135730"
    name: Coatue Management
  - id: "1061165"
    name: Lone Pine Capital
  - id: "1061768"
    name: The Baupost Group
  - id: "1167483"
    name: Tiger Global Management
  - id: "1103804"
    name: Viking Global Investors
